---
name: Net-FireEagle
version: 1.0
author:
  - 'Aaron Straup Cope  E<lt>ascope@cpan.orgE<gt>'
abstract: Object methods for working with the FireEagle location service.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Config::Simple: 0
  Digest::SHA1: 0
  LWP::UserAgent: 0
  Log::Dispatch: '>= 2.10'
  Readonly: 0
  URI: 0
  XML::XPath: '>= 1.13'
build_requires:
  Test::Simple: '>= 0.47'
provides:
  Net::FireBagel:
    file: lib/Net/FireBagel.pm
  Net::FireEagle:
    file: lib/Net/FireEagle.pm
    version: 1.0
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
